### ISSUE TITLE
Mudança logo Energife na página inicial

### ISSUE THREAD

**Issue by waicampos** [waicampos/macde-frontend#13]
O Energif mudou o nome para Energife e também a logo.

![image](https://github.com/waicampos/macde-frontend/assets/105655939/8ec70de4-1162-4b73-9edb-ea3a33a7f2a8)

### Tarefa:
- Alterar a logo do Energif na página inicial
![image](https://github.com/waicampos/macde-frontend/assets/105655939/66dd3137-fcb5-4f4e-a012-03719c436d0b)

**Comment by waicampos** [comment]
Tarefa Concluída

**Comment by danilosaes** [comment]
O logo foi alterado com sucesso, mas ainda falta alterar o nome ENERGIF para energife no site e no texto explicativo
## Antes


## Depois

**Comment by danilosaes** [comment]
O logo foi alterado com sucesso, porém ainda precisa mudar o nome ENERGIF para energife no título e no texto

## Antes
![image](https://github.com/waicampos/macde-frontend/assets/143753063/e5a4277c-82af-47c1-bb5b-67ad48cacfb0)


## Depois
![image](https://github.com/waicampos/macde-frontend/assets/143753063/42c752a8-4fa3-4bf9-a84c-3f3ffead73c2)

**Comment by danilosaes** [comment]
Feito!
