### ISSUE TITLE
Inserir mais opções de preenchimento na previsão de crescimento

### ISSUE THREAD

**Issue by danilosaes** [waicampos/macde-frontend#16]
Na etapa de parâmetros auxiliares, na parte da previsão de crescimento, adicionar uma "caixinha" para cada uma das quatro grandezas que temos: Demanda ou Demanda de Ponta, Demanda Fora de Ponta, Energia de Ponta e Energia Fora de Ponta.

## Antes
![image](https://github.com/waicampos/macde-frontend/assets/143753063/28c09be3-ee6f-4a9d-ba21-59a9612edf9d)

## Depois
![image](https://github.com/waicampos/macde-frontend/assets/143753063/bafd6517-8c28-4118-9117-2be99dd7776b)

**Comment by waicampos** [comment]
@tenfendaniel @danilosaes ter a opção para os 7 valores igual a tarifa?

**Comment by tenfendaniel** [comment]
São 7 caixas

**Comment by waicampos** [comment]
Tarefa concluída.



![Image](https://github.com/waicampos/macde-frontend/assets/105655939/ed5d1e93-3af2-43dd-8ac4-4987501091f2)
