### ISSUE TITLE
Retirar uma opção de preenchimento na área de demanda contratada

### ISSUE THREAD

**Issue by danilosaes** [waicampos/macde-frontend#17]
Na etapa de parâmetros auxiliares, na parte de demanda contratada, deixar apenas duas opções de preenchimento, ao invés de três. As opções teriam os nomes de Demanda ou Demanda de Ponta e Demanda Fora de Ponta.

## Antes
![image](https://github.com/waicampos/macde-frontend/assets/143753063/fb3caa55-b153-453d-b1b4-758d9024f754)

## Depois
![image](https://github.com/waicampos/macde-frontend/assets/143753063/63d820b6-8672-4e8e-a9c9-17072cc142f8)

**Comment by waicampos** [comment]
@danilosaes  @tenfendaniel não seria melhor manter os três valores? Talvez apenas alterar para Demanda verde, Demanda Fora de Ponta Azul e Demanda Ponta Azul.

**Comment by tenfendaniel** [comment]
Mantém 3
Demanda Verde
Demanda de Ponta Azul
Demanda Fora de Ponta Azul

**Comment by waicampos** [comment]
Tarefa concluída.



![Image](https://github.com/waicampos/macde-frontend/assets/105655939/f0ac6c96-0aba-42b6-b914-9261eb6ed9c9)
