### ISSUE TITLE
Alterar visualização dos dados históricos quando o parâmetro "Possui Sistema Fotovoltaico" estiver ativado

### ISSUE THREAD

**Issue by waicampos** [waicampos/macde-frontend#20]
Quando o usuário ativar a opção Possui Sistema Fotovoltaico, os dados do histórico deverão ter a visualização alterada. Todos os dados com data inferior a data de instalação do sistema fotovoltaico, informada pelo usuário, deverão ter cores diferentes, indicando que os dados não serão utilizados nos cálculos.

### Tarefa

- [x] Alterar a visualização no gráfico dos dados históricos;
- [x] Alterar a visualização na tabela dos dados históricos;

**Comment by danilosaes** [comment]
**FUNCIONA**
