### ISSUE TITLE
Avisar o usuário quando a etapa de previsão deverá ser refeita

### ISSUE THREAD

**Issue by danilosaes** [waicampos/macde-frontend#22]
Caso o usuário ative a opção "Possui Sistema Fotovoltaico" depois de já ter feito a/as etapa/etapas de previsão (ou também de otimização), é necessário exibir uma mensagem de aviso para que ele retorne e refaça a etapa de previsão de demanda para que, após isso, a etapa de otimização seja acessada.

**Comment by waicampos** [comment]
Concluído. Agora quando o cliente habilitar a opção de sistema fotovoltaico ou alterar a data de instalação é realizada a validação dos dados. Para dados inválidos aparece uma mensagem na página de Previsão, não sendo possível utilizar os modelos, apenas o file upload.

**Comment by danilosaes** [comment]
ok!
