### ISSUE TITLE
Inserção de ícones para textos explicativos

### ISSUE THREAD

**Issue by danilosaes** [waicampos/macde-frontend#23]
Atualmente, os textos explicativos estão fixos em cada etapa a ser realizada. Ao invés disso, deve ser colocado um ícone que, quando o usuário colocar o cursor em cima, mostre o texto.

## Como está agora
![image](https://github.com/waicampos/macde-frontend/assets/143753063/3de954db-00da-43d8-84b9-ce03fceaa394)

## Como ficará
![image](https://github.com/waicampos/macde-frontend/assets/143753063/1b16e7da-5295-4e23-bb90-f627173d2a86)

**Comment by waicampos** [comment]
Tarefa concluída.

### Texto desativado:
![Image](https://github.com/waicampos/macde-frontend/assets/105655939/021f4161-6f1c-4727-9da2-8e32487b6fdc)

### Texto ativado:
![Image](https://github.com/waicampos/macde-frontend/assets/105655939/5e8f54d7-02c7-48d7-b147-0d7ff669eaf7)

**Comment by waicampos** [comment]
Adicionado texto explicativo na página histórico e na Página Forecast.


![Image](https://github.com/waicampos/macde-frontend/assets/105655939/745555b0-214b-4740-9eb6-8a671fa0acc6)

![Image](https://github.com/waicampos/macde-frontend/assets/105655939/1a662950-6386-4913-be7b-b6cbf5139859)

**Comment by danilosaes** [comment]
Funcionando.
