### ISSUE TITLE
Parâmetro de Tributação: trocar "others" por "outros"

### ISSUE THREAD

**Issue by danilosaes** [waicampos/macde-frontend#24]
Apenas traduzir "others" para "outros" na área de preenchimento no parâmetro de Tributação
## Antes
![image](https://github.com/waicampos/macde-frontend/assets/143753063/8b8b6cd3-6d6f-49b8-b470-fbbe0c275c80)

## Depois
![image](https://github.com/waicampos/macde-frontend/assets/143753063/40c71718-bfe4-4cd8-99b7-332b147352ee)

**Comment by waicampos** [comment]
Tarefa concluída.

**Comment by danilosaes** [comment]
Feito!
