### ISSUE TITLE
Permitir que os campos dos parâmetros auxiliares aceitem valores negativos

### ISSUE THREAD

**Issue by danilosaes** [waicampos/macde-frontend#25]
Principalmente na etapa de tributação, permitir que o usuário possa preencher as caixinhas com valores negativos.

**Comment by waicampos** [comment]
Foi realizado alteração na forma de apresentação e validação dos dados. Na nova versão, quando o usuário digita um valor é realizada uma validação para ver se o valor digitado é um número válido. Caso contrário irá aparecer uma mensagem de erro na respectiva entrada de texto. Caso exista algum erro em algum campo, do grupo em questão, não é possível salvar os dados.

São realizadas duas validações:
- Requerido: é obrigatório o preenchimento do campo, não sendo permitido deixá-lo em branco;
- Formato número português: é verificado se o número digitado é válido. É utilizado o seguinte padrão: 
`/^(-|\+)?([0-9]*(,?[0-9]*))$/`

> **Validações** do número:
> - É permitido os caracteres de adição e subtração apenas no inicio do texto (apenas um deles ao mesmo tempo ou nenhum);
> - A vírgula é utilizada como separador decimal. Não é permitido ponto;
> - Apenas números são aceitos, com exceção dos caracteres: vírgula, adição e subtração.

### Recomendação para os testes:
@danilosaes nos testes a serem realizados é necessário testar outras coisas além do sinal negativo:

1. validar o erro gerado quando o campo é deixado em branco 

2. validar a lógica de aceitação de apenas números no formato brasileiro.  Exemplo de números válidos:

- ,3
- -253,32
- +96
- -0,0026

**Comment by danilosaes** [comment]
## Erro gerado quando o campo é deixado em branco:
![Image](https://github.com/waicampos/macde-frontend/assets/143753063/649061f5-e7ef-404e-aa83-a341a405049d)

## Erro gerado quando o número está no formato errado (. no lugar de ,):
![Image](https://github.com/waicampos/macde-frontend/assets/143753063/8989a846-2a36-4a97-80f5-23d8fd1823c0)

## Erro gerado quando o número está no formato errado (utilização de letras):
![Image](https://github.com/waicampos/macde-frontend/assets/143753063/901062f5-f347-4c15-9a82-b20c3f3fac57)

## Todas as validações estão funcionando.
