### ISSUE TITLE
Mudanças na página de Otimização

### ISSUE THREAD

**Issue by danilosaes** [waicampos/macde-frontend#26]
Duas coisas precisam ser implementadas/alteradas na página da etapa de Otimização.
Tal qual foi feito para a etapa de previsão no site antigo, colocar um aviso na etapa de otimização quando os dados necessários para a simulação não tiverem sido preenchidos (como o histórico ou os parâmetros auxiliares).
Além disso, trocar o nome da caixa de seleção de "Modalidade Tarifária" para "Tipo de Simulação".

## Como está
![image](https://github.com/waicampos/macde-frontend/assets/143753063/26d7dea5-c5c6-40ff-9895-f6c5e9748076)

## Como ficará
![image](https://github.com/waicampos/macde-frontend/assets/143753063/df452114-660d-47ab-b2bc-6e790a736e81)

**Comment by waicampos** [comment]
Tarefa concluída.

### Observações:
- Quando o usuário trocar o tipo de simulação no menu suspenso, os dados da previsão são automaticamente apagados, sendo necessário realizar a previsão novamente;
- Quando o usuário clicar em limpar dados, na página histórico, os dados de previsão são apagados.
- O Menu suspenso do Tipo de Simulação foi retirado da página otimização.
- O Botão otimizar aparece apenas quando há dados de previsão e o gráfico e a tabela são exibidos apenas quando há dados de previsão e há dados de otimização. Caso contrário, em ambos os casos,  aparece a mensagem de erro.
- A mensagem de erro foi alterada: 
> ANTES: 
> **"Não há dados previstos. É necessário realizar a previsão dos dados antes da otimização."**
>
> DEPOIS:
> **"Não há dados previstos ou houve alteração no valor do tipo de simulação. É necessário realizar a previsão dos dados antes da otimização."**

**Comment by danilosaes** [comment]
Funcionando
