### ISSUE TITLE
Trocar a posição das etapas de Informações e Relatório

### ISSUE THREAD

**Issue by danilosaes** [waicampos/macde-frontend#27]
Colocar a etapa de Informações antes da etapa de Relatório
## Como está
![image](https://github.com/waicampos/macde-frontend/assets/143753063/86ce7209-7f57-4785-a2b3-ac786d907474)

## Como ficará
![image](https://github.com/waicampos/macde-frontend/assets/143753063/58585e27-fbb0-4418-9bea-f635a25a1ba3)

**Comment by waicampos** [comment]
Tarefa Concluída

**Comment by danilosaes** [comment]
Feito!
