### ISSUE TITLE
Padronização dos gráficos na página de previsão

### ISSUE THREAD

**Issue by waicampos** [waicampos/macde-frontend#30]
Deixar os gráficos da página de otimização na mesma posição que os gráficos da página inicial.

**Comment by waicampos** [comment]
Tarefa concluída. Foi adicionado o gráfico sobre a tabela.

![image](https://github.com/waicampos/macde-frontend/assets/105655939/784015d5-fa41-450d-a78d-903cbe24cc26)

**Comment by danilosaes** [comment]
Funcionando
